baseURL: https://convolv.es/
languageCode: en-gb
title: J. Ryan Stinnett
theme: papermod
enableRobotsTXT: true
paginate: 5

params:
  dateFormat: "2006-01-02"

permalinks:
  post: /blog/:year/:month/:day/:filename/

markup:
  goldmark:
    renderer:
      unsafe: true
