baseURL: https://convolv.es/
languageCode: en-gb
title: J. Ryan Stinnett
theme: papermod
enableRobotsTXT: true
paginate: 5

params:
  env: production
  description:
    Exploring how to make programs more malleable and computing more humane
  dateFormat: "2006-01-02"
  homeInfoParams:
    title: "Hello! 👋 😄"
    content: |
      I enjoy building tools as part of a community that empowers domain experts
      to control and modify their digital workflows by tearing down the
      boundaries typically imposed by siloed applications from different
      vendors.

      I am organising the [Malleable Systems
      Collective](https://malleable.systems), a community that catalogs and
      experiments with malleable software and systems.

      I am researching reliable debugging and malleable software with [Dr.
      Stephen Kell](https://www.humprog.org/~stephen/) at King's College London.

      I previously worked at [Element](https://element.io) building open,
      decentralized, secure communications for all via
      [Matrix](https://matrix.org). I also worked at
      [Mozilla](https://www.mozilla.org) on developer tools for Firefox,
      and I overhauled the Firefox
      [CSS system](https://wiki.mozilla.org/Quantum/Stylo) using
      [Rust](https://www.rust-lang.org) and tech from
      [Servo](https://servo.org).
  socialIcons:
    - name: rss
      url: "/atom.xml"
    - name: email
      url: "mailto:jryans@gmail.com"
    - name: mastodon
      url: "https://merveilles.town/@jryans"
    - name: matrix
      url: "https://matrix.to/#/@jryans:matrix.org"
    - name: github
      url: "https://github.com/jryans"
  showFullTextInRSS: true
  mainSections:
    - blog
    - guides
    - talks

frontmatter:
  lastmod:
    - lastmod

permalinks:
  blog: /blog/:year/:month/:day/:filename/
  tags: /blog/tags/:title/

outputs:
  home:
    - HTML
    - RSS
    - JSON

outputFormats:
  RSS:
    baseName: "atom"

markup:
  goldmark:
    renderer:
      unsafe: true
