baseURL: https://convolv.es/
languageCode: en-gb
title: J. Ryan Stinnett
theme: papermod
enableRobotsTXT: true
paginate: 5

params:
  env: production
  description:
    Exploring how to make programs more malleable and computing more humane
  dateFormat: "2006-01-02"
  homeInfoParams:
    title: "Hello! 👋 😄"
    content: |
      I enjoy building tools as part of a community that empowers domain experts
      to control and modify their digital workflows by tearing down the
      boundaries typically imposed by siloed applications from different
      vendors.

      I am organising the [Malleable Systems
      Collective](https://malleable.systems), a community that catalogs and
      experiments with malleable software and systems.

      I am currently building open, decentralized, secure communications for all
      via [Matrix](https://matrix.org) at [Element](https://element.io) in
      London, UK.

      I previously worked at [Mozilla](https://www.mozilla.org) on [developer
      tools](https://twitter.com/FirefoxDevTools) for Firefox and Firefox OS.

      I also worked on overhauling the Firefox [CSS
      system](https://wiki.mozilla.org/Quantum/Stylo) using
      [Rust](https://www.rust-lang.org) and tech from
      [Servo](https://servo.org).
  socialIcons:
    - name: rss
      url: "/atom.xml"
    - name: twitter
      url: "https://twitter.com/jryans"
    - name: github
      url: "https://github.com/jryans"
  showFullTextInRSS: true

permalinks:
  /:    /blog/:filename/
  blog: /blog/:year/:month/:day/:filename/
  tags: /blog/tags/:title/

outputs:
  home:
    - HTML
    - RSS
    - JSON

outputFormats:
  RSS:
    baseName: "atom"

markup:
  goldmark:
    renderer:
      unsafe: true
