baseURL: https://convolv.es/
languageCode: en-gb
title: J. Ryan Stinnett
theme: papermod
enableRobotsTXT: true
paginate: 5

params:
  env: production
  description:
    Exploring how to make programs more malleable and computing more humane
  author: J. Ryan Stinnett
  dateFormat: "2006-01-02"

permalinks:
  post: /blog/:year/:month/:day/:filename/

markup:
  goldmark:
    renderer:
      unsafe: true
